-- ==========================================================
-- Revenue by Plan
-- Calculate the total deposit volume generated by each plan.
-- ==========================================================

SELECT u.plan, ROUND(SUM(e.deposit_amount),2) AS revenue
FROM users u JOIN events e ON u.user_id = e.user_id
WHERE e.event = 'first_deposit'
GROUP BY u.plan
ORDER BY revenue DESC;



-- ==========================================================
-- Revenue by Country
-- Calculate the total deposit volume generated by each country.
-- ==========================================================

SELECT u.country, ROUND(SUM(e.deposit_amount),2) AS revenue
FROM users u JOIN events e ON u.user_id = e.user_id
WHERE e.event = 'first_deposit'
GROUP BY u.country
ORDER BY revenue DESC;

-- ==========================================================
-- Revenue by Device
-- Calculate the total deposit volume generated by each device.
-- ==========================================================

SELECT u.device, ROUND(SUM(e.deposit_amount),2) AS revenue
FROM users u JOIN events e ON u.user_id = e.user_id
WHERE e.event = 'first_deposit'
GROUP BY u.device
ORDER BY revenue DESC;


-- ==========================================================
-- Revenue by Acquisition Channel
-- Calculate the total deposit volume generated by each acquisition channel.
-- ==========================================================

SELECT u.acquisition_channel, ROUND(SUM(e.deposit_amount),2) AS revenue
FROM users u JOIN events e ON u.user_id = e.user_id
WHERE e.event = 'first_deposit'
GROUP BY u.acquisition_channel
ORDER BY revenue DESC;

-- ==========================================================
-- Top 10 Largest Deposits
-- Retrieve the users with the highest first deposit amounts.
-- ==========================================================

SELECT u.user_id, u.plan, u.country, e.deposit_amount 
FROM users u JOIN events e ON u.user_id = e.user_id
WHERE e.event = 'first_deposit'
ORDER BY e.deposit_amount DESC
LIMIT 10;


